"""Generate the submission codebook for data/lots.csv.

Renders scripts/codebook_schema.py into codebook.md + codebook.html with live
row/missing counts from the actual CSV. Asserts the CSV header matches the
schema exactly (set + order) so the codebook can never silently drift from
the data it documents.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pandas as pd
from jinja2 import Template

from scripts.codebook_schema import COLUMNS, EXPECTED_HEADER


def check_header(lots_csv: Path) -> list[str]:
    """Read just the CSV header and fail loudly if it drifted from the schema."""
    header = list(pd.read_csv(lots_csv, nrows=0).columns)
    if header != EXPECTED_HEADER:
        missing = [c for c in EXPECTED_HEADER if c not in header]
        extra   = [c for c in header if c not in EXPECTED_HEADER]
        print("[codebook] lots.csv header does not match codebook_schema.EXPECTED_HEADER", file=sys.stderr)
        if missing:
            print(f"[codebook]   in schema but not in CSV: {missing}", file=sys.stderr)
        if extra:
            print(f"[codebook]   in CSV but not in schema: {extra}", file=sys.stderr)
        if not missing and not extra:
            print(f"[codebook]   same columns, different order:\n"
                  f"[codebook]   CSV:    {header}\n"
                  f"[codebook]   schema: {EXPECTED_HEADER}", file=sys.stderr)
        sys.exit(2)
    return header


def live_counts(lots_csv: Path) -> tuple[int, dict[str, int]]:
    df = pd.read_csv(lots_csv)
    return len(df), {c: int(df[c].isna().sum()) for c in df.columns}


MD = Template("""\
# Codebook — `data/lots.csv`

**Project:** DirectIndexing — learning the tax-loss-harvest decision boundary
**Dataset:** {{ n_rows }} rows × {{ columns|length }} columns. One row = one *lot snapshot*:
the state of a single tax lot on a single simulated trading day.

Rows are produced by the backtesting simulation (`dotnet run simulate`) over a
$10M equal-dollar S&P 500 portfolio driven by real daily prices (Financial
Modeling Prep API). Features describe the lot, the asset, and the shared
portfolio state; labels record whether/with what propensity the deterministic
harvesting oracle fires. Metadata columns are dropped before modeling.

Missing values are written as empty cells in the CSV and read as NaN.

{% for c in columns %}
## {{ loop.index }}. `{{ c.name }}`

| | |
|---|---|
| **Type** | {{ c.dtype }} |
| **Units** | {{ c.units }} |
| **Role** | {{ c.role }} |
| **Values / encoding** | {{ c.encoding }} |
| **Missing** | {{ c.missing }}{% if na_counts[c.name] %} — observed: {{ na_counts[c.name] }} of {{ n_rows }} rows ({{ "%.2f"|format(100 * na_counts[c.name] / n_rows) }}%){% endif %} |
| **Source** | `{{ c.source }}` |

{{ c.description }}
{% endfor %}

---
*Generated by `scripts/codebook.py` from `scripts/codebook_schema.py`; the
generator asserts the schema matches the CSV header, so this document always
reflects the shipped dataset.*
""")

HTML = Template("""\
<!doctype html>
<html><head>
<meta charset="utf-8">
<title>Codebook — lots.csv</title>
<style>
 body { font-family: -apple-system, system-ui, sans-serif; max-width: 1000px; margin: 2em auto; padding: 0 1em; color: #222; }
 h1 { border-bottom: 2px solid #357; padding-bottom: .3em; }
 h2 { color: #357; margin-top: 1.6em; }
 table { border-collapse: collapse; margin: 1em 0; width: 100%; }
 th, td { border: 1px solid #ddd; padding: 6px 12px; text-align: left; vertical-align: top; }
 th { background: #f5f5f5; width: 11em; }
 code { background: #f5f5f5; padding: 1px 4px; border-radius: 3px; }
 .note { color: #777; font-size: .9em; }
</style></head><body>

<h1>Codebook — <code>data/lots.csv</code></h1>
<p><strong>{{ n_rows }}</strong> rows × <strong>{{ columns|length }}</strong> columns.
One row = one <em>lot snapshot</em>: the state of a single tax lot on a single
simulated trading day. Missing values are empty cells (NaN).</p>

{% for c in columns %}
<h2>{{ loop.index }}. <code>{{ c.name }}</code></h2>
<table>
 <tr><th>Type</th><td>{{ c.dtype }}</td></tr>
 <tr><th>Units</th><td>{{ c.units }}</td></tr>
 <tr><th>Role</th><td>{{ c.role }}</td></tr>
 <tr><th>Values / encoding</th><td>{{ c.encoding }}</td></tr>
 <tr><th>Missing</th><td>{{ c.missing }}{% if na_counts[c.name] %} — observed: {{ na_counts[c.name] }} of {{ n_rows }} rows ({{ "%.2f"|format(100 * na_counts[c.name] / n_rows) }}%){% endif %}</td></tr>
 <tr><th>Source</th><td><code>{{ c.source }}</code></td></tr>
</table>
<p>{{ c.description }}</p>
{% endfor %}

<p class="note">Generated by <code>scripts/codebook.py</code> from
<code>scripts/codebook_schema.py</code>; the generator asserts the schema
matches the CSV header, so this document always reflects the shipped dataset.</p>
</body></html>
""")


def generate(lots_csv: Path, out_dir: Path) -> tuple[Path, Path]:
    """Generate codebook.md + codebook.html; returns the two output paths."""
    check_header(lots_csv)
    n_rows, na_counts = live_counts(lots_csv)
    out_dir.mkdir(parents=True, exist_ok=True)

    ctx = dict(columns=COLUMNS, n_rows=n_rows, na_counts=na_counts)
    md_path   = out_dir / "codebook.md"
    html_path = out_dir / "codebook.html"
    md_path.write_text(MD.render(**ctx))
    html_path.write_text(HTML.render(**ctx))
    return md_path, html_path


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--lots", required=True, help="path to data/lots.csv")
    ap.add_argument("--out",  required=True, help="output directory")
    args = ap.parse_args()

    md_path, html_path = generate(Path(args.lots), Path(args.out))
    print(f"[codebook] wrote {md_path} and {html_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
